version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - 1.15.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: com.squareup.leakcanary:leakcanary-android
    versions:
    - "2.6"
  - dependency-name: com.squareup.okhttp3:mockwebserver
    versions:
    - 4.9.0
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - 4.9.0
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: org.threeten:threetenbp
    versions:
    - 1.5.0
  rebase-strategy: disabled
